export enum OrderStatusEnum {
  PENDING = 1,
  TRADER1_DEPOSIT = 2,
  CUSTOMER_SENT = 3,
  TRADER_RECEIVED = 4,
  TRADER_PAID = 5,
  ORDER_FINISHED = 6,
  TRADER2_PARTICIPATED = 7,
  CANCELED = 8,
  COMPLETED = 9,
  VIEWING = 10,
  DISPUTE = 11,
}
